language: node_js
cache: npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

stages:
  - name: greenkeeper-routes-update
    if: type IN (push) AND branch =~ ^greenkeeper/@octokit/routes
  - name: prettier-update
    if: type IN (push) AND branch =~ ^greenkeeper/prettier
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    # when updating @octokit/routes, run "generate-types" script and push
    # updated types to the pull request
    - stage: greenkeeper-routes-update
      node_js: lts/*
      script:
        - git checkout $TRAVIS_BRANCH
        - npm run generate-types
        # commit changes and push back to branch on GitHub. If there are no changes then exit without error
        - 'git commit src/generated/routes.ts -m "fix(typescript): updated endpoint route & parameter definitions" --author="Octokit Bot <octokitbot@martynus.net>" && git push "https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG" ${TRAVIS_BRANCH} || true'
    - stage: prettier-update
      node_js: lts/*
      script:
        - git checkout $TRAVIS_BRANCH
        - npm run lint:fix
        - 'git commit -v -a -m "style: prettier" --author="Octokit Bot <octokitbot@martynus.net>" && git push "https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG" ${TRAVIS_BRANCH} || true'

    - stage: test
      node_js: 8
      script: npm run test
    - node_js: 10
      script: npm run test
    - node_js: 12
      script: npm run test

    # release stage: run semantic release & update the docs
    - stage: release
      node_js: lts/*
      env: semantic-release
      script:
        - npm run build
        - npx semantic-release
